### ISSUE TITLE
[TASK] Relabel credential parameters with source and destination

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-copado#100]
Advanced case for #27 : 

2 or more **instances** with multiple BUs with 1 credential name (deployment user).
These properties are linked to the pipeline:
None

These properties are linked to the environment:

1. tenant
2. clientId
3. clientSecret
4. credentialName/BUId
5. enterpriseID

should come from source & destination (environment)

**expected changes:**

- [x] copado function parameters
- [x] copado job template (edit + save)
- [ ] Deploy.env
- [x] Deploy.env-sample
- [x] Deploy.config
- [x] Deploy.js

**Comment by DannyCastroVentura** [comment]
At the moment, as I am not sure which are the values for the target env variables, I did:

- In server:
  - Added the target credentials in the copado function parameters with the source values;
  - Saved the copado job template (to avoid the undefined bug);
- In git branch:
  - Updated the deploy.js to use the target env variables in the target's credentials
  - updated the deploy.config

When got clairvoyance from @JoernBerkefeld will change this to the proper values

**Comment by JoernBerkefeld** [comment]
hint:
```javascript
const CONFIG = {
    credentialNameSource: process.env.credentialNameSource,
    credentialNameTarget: process.env.credentialNameTarget,
    credentials: JSON.parse(process.env.credentials)
};


const credSource = CONFIG.credentials[CONFIG.credentialNameSource];
const credTarget = CONFIG.credentials[CONFIG.credentialNameTarget];
```

**Comment by JoernBerkefeld** [comment]
how environment system properties have to be set up:
![image](https://user-images.githubusercontent.com/1917227/195342155-255e0a89-79a6-4a7c-a521-78c4b49366b4.png)

**Comment by JoernBerkefeld** [comment]
how the function needs to be set up:
![image](https://user-images.githubusercontent.com/1917227/195342292-0d3b9ff5-bfa8-4155-ad38-324e0c0a6197.png)

**Comment by JoernBerkefeld** [comment]
and same for the job step:
![image](https://user-images.githubusercontent.com/1917227/195342424-cab9dee9-a2b3-4e9f-9d98-dceedbeb8738.png)

**Comment by JoernBerkefeld** [comment]
what needs to be removed from function parameters AND from job steps?
![image](https://user-images.githubusercontent.com/1917227/195342797-9806b9ce-fe2c-4a79-a0e2-8a51b6cb5fd7.png)

**Comment by JoernBerkefeld** [comment]
mapping- but probably not needed because we can just pass the new CONFIG.credentials to `provideMCDevCredentials()`


```
const mapping = {
    clientID: credSource.client_id,
    clientSecret: credSource.client_secret,
    tenant: credSource.auth_url, // potentiall difference! mct0l7nxfq2r988t1kxfy8sc47mq vs. https://mct0l7nxfq2r988t1kxfy8sc47mq.auth.marketingcloudapis.com/
    enterpriseId: credSource.account_id
}
```

**Comment by DannyCastroVentura** [comment]
> what needs to be removed from function parameters AND from job steps? ![image](https://user-images.githubusercontent.com/1917227/195342797-9806b9ce-fe2c-4a79-a0e2-8a51b6cb5fd7.png)

And the additional parameters that I added before right?

![image](https://user-images.githubusercontent.com/72609808/195347838-04163249-4caa-473b-ab9c-880bef344896.png)

**Comment by DannyCastroVentura** [comment]
> how the function needs to be set up: ![image](https://user-images.githubusercontent.com/1917227/195342292-0d3b9ff5-bfa8-4155-ad38-324e0c0a6197.png)



> and same for the job step: ![image](https://user-images.githubusercontent.com/1917227/195342424-cab9dee9-a2b3-4e9f-9d98-dceedbeb8738.png)

Added this for the **retrieve** and for the **deploy** in the **function parameters** and in **job steps**
