### ISSUE TITLE
[TASK] research Copado "Credential"

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-copado#102]
what is it?
do we need to create them for every user-environment combo?
do we need to change them back and forth in the user story if 2 users would work with that user story one after the other?
how do you set up a credential for a specific environment?

https://copadonull71743980.lightning.force.com/lightning/o/copado__Org__c/list?filterName=00B0900000L4V0aEAF

![image](https://user-images.githubusercontent.com/1917227/193053700-157e2338-f9bd-40eb-a1e9-c2c514f8b4aa.png)

**Comment by DannyCastroVentura** [comment]
**Q:** What is it:
**A:** A credential represents a user connection to an environment. When you create a credential, the level of access to the associated Salesforce org is the same as that of the username you are using to authenticate the credential.

<br>

**Q:** do we need to create them for every user-environment combo?
**A:** If with "user", you want to say "developer", then no, an environment is dependent on the credential, the developer is assign to the user-story.

You can see it in the [**Structure of a User Story**](https://docs.copado.com/articles/#!copado-ci-cd-publication/structure-of-a-user-story).

<br>

**Q:** do we need to change them back and forth in the user story if 2 users would work with that user story one after the other?
**A:** Credentials are not associated to the developers, but to the environments:

> Credential | The Credential is used to add or commit metadata, or to promote and deploy the user story to the next environment

> Environment | The current environment of the user story. This value is dependent on the value selected for the credential.

> Developer | The person who is currently working on the user story.

<br>

**Q:** how do you set up a credential for a specific environment?
**A:** It is very well explained in [**Create a Credential**](https://docs.copado.com/articles/#!copado-ci-cd-publication/how-to-create-a-credential)

**Comment by DannyCastroVentura** [comment]
@JoernBerkefeld can I close this issue?
