### ISSUE TITLE
[BUG] copado-git-get-mock error on create branch

### ISSUE THREAD

**Issue by DannyCastroVentura** [Accenture/sfmc-devtools-copado#132]
**Current Behavior**
  
While executing the `copado-git-get ${createBranch ? '--create ' : ''}"${workingBranch}"`, it gives an error if the branch is already created.

  
  
**Expected Behavior**
  
If the branch is already created, it should just checkout, if not it should create it and then checkout.

**Comment by JoernBerkefeld** [comment]
updated copado-git-get-mock to 2.0.3 which fixes all that.
