### ISSUE TITLE
[BUG] Child Env component now lists ALL other environments

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-copado#145]
**Current Behavior**
![image](https://user-images.githubusercontent.com/1917227/194761150-768d960f-f409-4c56-bf97-97ec43b741fe.png)

**Expected Behavior**
  
what we saw before - only entries are listed that have the current record set up as parent?!
  
  
**Steps To Reproduce**
  
  1. open any environment, e.g. https://copadonull71743980.lightning.force.com/lightning/r/copado__Environment__c/a0V09000007ILf2EAG/view

**Comment by Rishabh02git** [comment]
Issue Fixed 

Uploading the latest Version of the code from code to the environment fixed the issue
