### ISSUE TITLE
[BUG] git diff in commit.js does not see changed components

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-copado#150]
**Current Behavior**
2 dataextensions selected, of which 1 was new. the other unchanged. 0 changes were found by commit.js
  
  
**Expected Behavior**
  
1 change found.

  
  
**Steps To Reproduce**

result record:
https://copadonull71743980.lightning.force.com/lightning/r/copado__Result__c/a0z09000003FZlGAAW/view

1. make change / add 1 dataextension.
2. select this one and another one on commit page
3. execute commit
4. check logs

**Comment by DannyCastroVentura** [comment]
fixed w/ #152 #151

**Comment by JoernBerkefeld** [comment]
closed by #152
