### ISSUE TITLE
[FEATURE] update retrieve/target-bu on "master" branch as part of deploy

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-copado#154]
_Originally posted by @JoernBerkefeld in https://github.com/Accenture/sfmc-devtools-copado/issues/130#issuecomment-1273429522_
in deploy step we will update the folder retrieve/target-bu/ - right now we don't and that's causing us to lose information.

**solution**: after successful deploy, run mcdev.retrieve() like shown in commit.js (it takes a list of types and keys and only downloads relevant information)

why not use what we push into deploy folder instead? because there are sometimes differences in the json format between deploy & retrieve

what's to do:

- [x] in Deploy.js, we ALWAYS use "master" as our destination branch. lets make sure we use CONFIG.mainBranch instead of CONFIG.destinationBranch everywhere
- [x] make sure main_branch gets its data via function parameter: `main_branch={$Pipeline.copado__Main_Branch__c}`
- [x] use code from commit.js to retrieve what was just deployed to our retrieve folder AND execute commit.

**Comment by DannyCastroVentura** [comment]
regarding the CONFIG.promotionBranch, we will still use it as it is?
