### ISSUE TITLE
[TEST] what kind of metadata is committed & deployed correctly?

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-copado#166]
- dataExtension
- script
- query
- automation
- automation activity types
- asset
- and more (TBD)

**Comment by DannyCastroVentura** [comment]
Tested and working:

- [ ]  dataExtension
- [ ] script
- [ ] query
- [ ] automation
- [ ] automation activity types
- [ ] asset
- [ ] and more (TBD)

**Comment by JoernBerkefeld** [comment]
updated checkboxes. all but "and more" is now tested and found working

**Comment by DannyCastroVentura** [comment]
Unchecked asset

**Comment by JoernBerkefeld** [comment]
confimed asset is working correctly now. closing task
