### ISSUE TITLE
[BUG] Mass Back Promote empty fields

### ISSUE THREAD

**Issue by DannyCastroVentura** [Accenture/sfmc-devtools-copado#169]
**Current Behavior**
  
When we try to use the Mass Back Promote, we are sent to a new page when we need to choose a Source Environment, a Project and a Release.

Problem: All of this dropdown lists are empty:

![image](https://user-images.githubusercontent.com/72609808/195797012-c7827973-b627-4134-8ec4-b672405fe4ef.png)
![image](https://user-images.githubusercontent.com/72609808/195797036-1030b12b-ec32-43ab-9687-bcc635543150.png)
![image](https://user-images.githubusercontent.com/72609808/195797050-67bed246-2693-41c3-b1b3-f9362ba6de21.png)

**Comment by JoernBerkefeld** [comment]
@nrabe-copado is looking into it

**Comment by JoernBerkefeld** [comment]
solution: one needs to set the Environment.Type field to **Sandbox** for all environments that are on the left in pipeline manager and to **Production/Developer** for the one on the right.



![Image](https://user-images.githubusercontent.com/1917227/195856409-9a83d615-9d95-4a1a-ac79-c25e0946599b.png)
