### ISSUE TITLE
[FEATURE] docker container that has dependencies preinstalled

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-copado#17]
requirement for Copado rather than for this toolset but @uwe-voellger brought it up quite some time ago and I believe it's still valid. Relying on installing software each time we execute a command reduces the UX immensely

**Comment by DannyCastroVentura** [comment]
Docker images: 
 - 0onz6fxsbyolcopmojdzlxa5vzgsts-sfmc-devtools:v1.0.0-develop
 - 0onz6fxsbyolcopmojdzlxa5vzgsts-sfmc-devtools:v1.0
