### ISSUE TITLE
[BUG] Back Promote fails on missing production branch

### ISSUE THREAD

**Issue by DannyCastroVentura** [Accenture/sfmc-devtools-copado#170]
**Current Behavior**
  
https://copadonull71743980.lightning.force.com/lightning/r/copado__Result__c/a0z09000003FaBLAA0/view

**Comment by JoernBerkefeld** [comment]
if we could overwrite the validation on pipeline connections that branches can only be used once, we could set up "master" there instead and our promote function would work

**Comment by JoernBerkefeld** [comment]
probably found a solution together with @nrabe-copado - hardwired this in the promote step parameters:


![Image](https://user-images.githubusercontent.com/1917227/195804267-5880a215-f2b9-4682-8ee2-5a3f9f5ee8c3.png)

**Comment by JoernBerkefeld** [comment]
and job template updated: 


![Image](https://user-images.githubusercontent.com/1917227/195804715-19485c24-fdf3-4937-89d3-d94079b7ac0c.png)

**Comment by JoernBerkefeld** [comment]
initial test is good 


![Image](https://user-images.githubusercontent.com/1917227/195806112-73c0f1f1-e455-4ccd-a9ac-36bce89c13fc.png)

**Comment by JoernBerkefeld** [comment]
all working fine
