### ISSUE TITLE
[BUG] retrieve in retrieveTable should return folders

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-copado#211]
as of now we skip folders because that would mean we need to cache folders and process the metadata at least for that - which takes time.
however, knowing the folder something is in provides valuable context and hence we should add that.
also, the standard "**User Story Metadata**" entry offers the field **Directory** to store that - we would need to know what the field name needs to be for that though.

![image](https://user-images.githubusercontent.com/1917227/196843833-240b6c49-8ff7-4a79-ab3e-5be00a8c21ad.png)

maybe we can limit it to something during the commit step, in which we get the full metadata anyways? depends on how these records are created.
any thoughts @nrabe-copado ?

**Comment by nrabe-copado** [comment]
The Directory field is to store the relative directory name of the element .

so, if you have a commit with two changes:

README.md
src/main/index.js

... then for the first item the Directory would be empty "", because it is in the root of the git repository.
and for the index.js file, Directory="src/main"

**Comment by JoernBerkefeld** [comment]
Understood - only that it is not auto filing that. My guess is that it is based on the response that our retrieveTable is sending to the commit overlay when we confirm the cimmit message- we send the list of files but without ab attribute for the directory

**Comment by JoernBerkefeld** [comment]
turns out it's the "m" field. found it here https://docs.copado.com/articles/#!copado-ci-cd-publication/executing-a-copado-action
