### ISSUE TITLE
[BUG] Deploy don't end

### ISSUE THREAD

**Issue by DannyCastroVentura** [Accenture/sfmc-devtools-copado#216]
**Current Behavior**
  
When deploying  dataExtension, automation, dataExtract, script and fileTransfer the function does not end (was 20 min saying "Completed download")

https://copadonull71743980.lightning.force.com/lightning/r/copado__Result__c/a0z09000003FacKAAS/view

  
  
**Expected Behavior**
  
Deploy the things, or at least throw some error because of timeout

**Comment by DannyCastroVentura** [comment]
Commited files:

- filetrasnfer, script and dataExtract -> work

- dataextension and automation -> work

- if all 5 in the same time -> we get this bug

**Comment by JoernBerkefeld** [comment]
pls add links to result/jobExecution

**Comment by DannyCastroVentura** [comment]
Now it seems that it is working: https://copadonull71743980.lightning.force.com/lightning/r/copado__Result__c/a0z09000003Fai0AAC/view

**Comment by DannyCastroVentura** [comment]
I guess this was an one time issue due to copado servers, I think we can close this. @JoernBerkefeld
