### ISSUE TITLE
[BUG] Retrieving failed: selectedTypesArr is not iterable - Commit.js

### ISSUE THREAD

**Issue by DannyCastroVentura** [Accenture/sfmc-devtools-copado#217]
**Current Behavior**
  
When using the docker image with the mcdev tools on the commit, we receive the following error message: **Retrieving failed: selectedTypesArr is not iterable**, maybe because the outdated version of mcdev tools on the docker image

**Comment by JoernBerkefeld** [comment]
due to old version of mcdev. to be expected as of now because the images uses **mcdev 4.0.2** and we've been working with the **latest unreleased version directly from the develop branch** in github.

closing as invalid
