### ISSUE TITLE
[BUG] Commit goes wrong if using assets

### ISSUE THREAD

**Issue by DannyCastroVentura** [Accenture/sfmc-devtools-copado#218]
**Current Behavior**
  
When commiting assets it says that there is no changes, **even if they are different versions of the asset**
If commiting only one asset it will retrieve an error saying "Nothing to commit"

  https://copadonull71743980.lightning.force.com/lightning/r/copado__Result__c/a0z09000003FahrAAC/view
![image](https://user-images.githubusercontent.com/72609808/197165337-1d0719e7-43cb-4860-936b-4e2990e624a4.png)

  
**Expected Behavior**
  
Only say "Nothing to commit" this when there is actually no change on the asset

**Comment by JoernBerkefeld** [comment]
restarting execution of the above result to reproduce error with more logs

via job execution: https://copadonull71743980.lightning.force.com/lightning/r/copado__JobExecution__c/a1y09000000cbaKAAQ/view

**Comment by JoernBerkefeld** [comment]
looks like getFilesToCommit is not processing the 1 asset that was downloaded 
![image](https://user-images.githubusercontent.com/1917227/197171314-bfd5e370-c066-4737-b704-477a6509d6ff.png)


digging into mcdev logs, one then sees that this is about the subtype asset-asset an in that the sub-sub-type "jsonmessage" which cant be processed at this time (or simply isn't yet)
![image](https://user-images.githubusercontent.com/1917227/197171590-c0237191-3985-462b-bf7a-43a53cb9ae7c.png)

**Comment by JoernBerkefeld** [comment]
looks like the issue was indeed caused by a problem in mcdev.getFilesToCommit.
issue tracked in https://github.com/Accenture/sfmc-devtools/issues/463
and fix shared: https://github.com/Accenture/sfmc-devtools/pull/464

**Comment by JoernBerkefeld** [comment]
fix tested successfully: https://copadonull71743980.lightning.force.com/lightning/r/copado__Result__c/a0z09000003Faj8AAC/view
**commit worked**
