### ISSUE TITLE
[BUG] filter dataextensions ending on "_Salesforce" or on "_Salesforce_1"

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-copado#227]
**Current Behavior**
  
all entries are returned to the retrievetable including shared dataextensions

  
  
**Expected Behavior**
  
we should filter a entries that cannot be deployed.
"Shared DataExtensions" are not deployable and hence we should not allow selection (nor show them).
These can be recognized by the suffix "_Salesforce" and optionally a secondary suffix "_n":

![image](https://user-images.githubusercontent.com/1917227/197517786-b21e923c-c815-4101-844f-c759e87eb69f.png)

I think this filter will do: `/(_Salesforce)(_\d)?$/g`

seems to work for both situations:
![image](https://user-images.githubusercontent.com/1917227/197518308-ea0e3ee8-e635-42a4-9966-ebb0f552983e.png)
![image](https://user-images.githubusercontent.com/1917227/197518341-009fb38b-fec3-471e-9aec-5cdacbe6bf03.png)

**Comment by DannyCastroVentura** [comment]
Should this one be prevented to show as well?



![Image](https://user-images.githubusercontent.com/72609808/197536878-26b90605-801b-4097-9dc2-574f5e50a3ca.png)

If yes, that regular expression would not work:



![Image](https://user-images.githubusercontent.com/72609808/197537093-5e0b95fb-e572-44ef-87aa-340fcaad9ada.png)

This would:



![Image](https://user-images.githubusercontent.com/72609808/197537244-d53c815e-7b87-4a60-a8cc-18a63fe3a395.png)

**Comment by DannyCastroVentura** [comment]
Couldn't test it

**Comment by JoernBerkefeld** [comment]
re-opening as pr is not merged / reviewed yet
