### ISSUE TITLE
[BUG] Cannot read properties of undefined (gitDiffArr) - deploy.js

### ISSUE THREAD

**Issue by DannyCastroVentura** [Accenture/sfmc-devtools-copado#243]
**Current Behavior**
  
If no changes are found, the program continues and throw an error on the Log.result.

[copadonull71743980.lightning.force.com/lightning/r/copado__Result__c/a0z09000003FawSAAS/view](https://copadonull71743980.lightning.force.com/lightning/r/copado__Result__c/a0z09000003FawSAAS/view)
  
**Log**
10:45:06	❌ Nothing to commit as all selected components have the same content as already exists in Git.
10:45:07	CopadoFunction INFO setting status 'Nothing to commit' error='Nothing to commit as all selected components have the same content as already exists in Git.'
10:45:07	❌ git commit failed:Nothing to commit
10:45:09	CopadoFunction INFO setting status 'Error' error='git commit failed:Nothing to commit'
10:45:09	⚠ Failed deploy verification, check BU on SFMC to verify manually. Git not updated with the changes on target BU: Nothing to commit
10:45:09	git-push changes
...
10:45:13	Finished
10:45:13	===================
10:45:13	Deploy.js done
10:45:13	/tmp/cf_function.sh:297
10:45:13	        `Deployed ${gitDiffArr.length} items ` + (verificationText ? ` (${verificationText})` : '')
10:45:13	                               ^
10:45:13	TypeError: Cannot read properties of undefined (reading 'length')
10:45:13	    at run (/tmp/cf_function.sh:297:32)

**Approach**
What shoud be the approach here? Assuming that it is quite impossible to be on deploy and have no changes, should we throw an error after a "nothing to commit"? Or should we change the code to something like "if(gitDiffArr === undefined)" and show a different message on Log.result?

**Comment by JoernBerkefeld** [comment]
fixed via pr #245
