### ISSUE TITLE
[BUG] Unknown error on deploy (not reproducable)

### ISSUE THREAD

**Issue by DannyCastroVentura** [Accenture/sfmc-devtools-copado#247]
**Current Behavior**
  
Retrieve is working fine, as it is commit, but on deploy it is throwing an error saying: 

- Deployment of BU Copado-MarkClDevOps/MCDEV_Training_Pre-Target failed. 

When in reality, it was deployed without any errors into the targetBU.

**Files tried to deploy:**
Daniel Ventura - DataExtension

**Result link:**
https://copadonull71743980.lightning.force.com/lightning/r/copado__Result__c/a0z09000003FazHAAS/view

**Log errors**

...
16:12:42	❌ Deploy failed: Deployment of BU Copado-MarkClDevOps/MCDEV_Training_Pre-Target failed. Please check the SFMC DevTools logs for more details.
16:12:44	CopadoFunction INFO setting status 'Error' error='Deploy failed: Deployment of BU Copado-MarkClDevOps/MCDEV_Training_Pre-Target failed. Please check the SFMC DevTools logs for more details.'
...
16:12:53	CopadoFunction INFO setting status 'Attached mcdev logs'
16:12:53	/tmp/cf_function.sh:1073
16:12:53	            throw new Error(
16:12:53	                  ^
16:12:53	Error: Deployment of BU Copado-MarkClDevOps/MCDEV_Training_Pre-Target failed. Please check the SFMC DevTools logs for more details.
16:12:53	    at Function.deployBU (/tmp/cf_function.sh:1073:19)
16:12:53	    at async run (/tmp/cf_function.sh:247:13)

**Log part which is saying what was deployed**

...
16:10:28	Deploy BUs
16:10:28	===================
16:10:28	: mcdev:: Deploy
16:10:28	: ::Deploying Copado-MarkClDevOps/MCDEV_Training_Pre-Target
16:10:28	: Caching dependent Metadata: folder
16:12:36	: - Connection problem (Code: ETIMEDOUT). Retrying 3 times
16:12:37	: Caching dependent Metadata: dataExtensionTemplate
16:12:37	: Caching dependent Metadata: dataExtension
16:12:38	:  - Caching dependent Metadata: dataExtension (shared via _ParentBU_)
16:12:38	:  - Caching dependent Metadata: folder (shared via _ParentBU_)
16:12:40	: Deploying: dataExtension
16:12:40	:  - Caching dependent Metadata: dataExtensionField
16:12:41	:  - Please note that Data Retention Policies can only be set during creation, not during update.
16:12:42	:  - updated dataExtension: Daniel Ventura /  Daniel Ventura
16:12:42	: dataExtension upsert: 0 of 0 created / 1 of 1 updated
16:12:42	: 
16:12:42	               :: Deployed 1 BUs
...

**Comment by JoernBerkefeld** [comment]
logs dont say that anything is wrong. somehow exitCode must have been 1 but the logs do not reveal why. No error was logged. **cannot reproduce.**
