### ISSUE TITLE
[BUG] Not refreshing status on commit after it is commited

### ISSUE THREAD

**Issue by DannyCastroVentura** [Accenture/sfmc-devtools-copado#251]
**Current Behavior**
  
Sometimes it doesn't refresh the status on commit, it happened for this result: https://copadonull71743980.lightning.force.com/lightning/r/copado__Result__c/a0z09000003Fb2SAAS/view

  
  
**Expected Behavior**
  
If it is completed, it should show the following message without a need for refresh the page:
![image](https://user-images.githubusercontent.com/72609808/197977778-40e3948f-ad08-4cb9-a6be-a9a39157b9a7.png)

This just happened this 1 time, lets see if it happens again in the future.

**Comment by JoernBerkefeld** [comment]
out of our control. issue with salesforce events and out-of-the-box copado code
