### ISSUE TITLE
[TASK] Relabel credential parameters with source and destination

### ISSUE THREAD

**Issue by drcopa** [Accenture/sfmc-devtools-copado#27]
The clientId, clientSecret, tenant and credential name, BUName parameters will be either part of source environment or destination environment. 

**Simple case is 1 instance with 2 BUs with 1 or more credential names (deployment user).** 
These properties are linked to the Pipeline:
1. tenant
2. clientId
2. clientSecret

These properties are linked to the environment:
1. credentialName/BUId

**Advanced case handled in #100**

**Comment by JoernBerkefeld** [comment]
![image](https://user-images.githubusercontent.com/1917227/192820245-657006d7-74f3-4378-b3f4-a0082d7b4830.png)
for our pilot client, we will see scenario 1+3 of the above graphic. scenario 2 is not relevant.

legend:
- orange = server/instance
- blue = credential (client id, client secret, credential name, tenant)
- green = business unit

**Retrieve.js:**
we only need the credential for the **source**

**Commit.js:**
we only need the credential for the **source**

**Deploy.js:**
_ideally,_ we only need the credential for the **target**. However, we likely need at least the **credential name** of the source to execute `buildTemplate` (via `createDeltaPkg`)

**Upgrade.js:**
nothing is needed

**Comment by JoernBerkefeld** [comment]
suggested change to all 4 files @DannyCastroVentura 
```js
    credentials: {
        source: {
            clientId: process.env.clientId,
            clientSecret: process.env.clientSecret,
            credentialName: process.env.credentialName,
            tenant: process.env.tenant,
        },
        target: {
            clientId: process.env.clientId,
            clientSecret: process.env.clientSecret,
            credentialName: process.env.credentialName,
            tenant: process.env.tenant,
        },
    },
    // clientId: process.env.clientId,
    // clientSecret: process.env.clientSecret,
    // credentialName: process.env.credentialName,
    // tenant: process.env.tenant,
```
