### ISSUE TITLE
[FEATURE] manage mcdev `markets` via copado GUI

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-copado#28]
acceptance criteria
- the user has to be able to create/edit/delete infinite amount of variables per ENVIRONMENT record
- MANUAL USER TASK ONLY: markets should be grouped to ensure that adding a variable in one market also adds/renames the similar variable in other markets of the same group
---> use Parent Environment for grouping if set

**important: ** should be handled already by the "childEnvironment..." components but you need to double check the if they work properly!

this task blocks #79

**Comment by anil-sfdc** [comment]
LWC ChildEnvironmentVariables working fine and discussed, so no need to do this US
