### ISSUE TITLE
Error Label "empApi" appears after several minutes of having refreshed

### ISSUE THREAD

**Issue by drcopa** [Accenture/sfmc-devtools-copado#3]
Steps to reproduce:
1. Open a marketing cloud user story
2. Click on Commit Changes
3. Click on Refresh
4. Leave the page open for 10 minutes
5. Come back to the page and you will see error message

Possible cause: the page remains listening to the result platform event even after the function result completed. To fix this unsubscribe from platform event as soon as the result completes and the table is rerendered. 

![EmpAPI Error Message](https://user-images.githubusercontent.com/25175105/149299769-909d8e09-0e8d-4d20-a98b-14f76533c40c.png)
e

**Comment by JoernBerkefeld** [comment]
ok - what was the outcome of your first analysis?

**Comment by anil-sfdc** [comment]
it dependent  103. Refresh issue need to be fix first.
