### ISSUE TITLE
[TEST] deploy changes/additions to existing config to 1-n BUs

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-copado#31]
request by Christine.

this is us testing our #2 pipeline:

1. create multiple changes
2. commit these into separate user stories (sometimes 2 changes, sometimes just 1 per US)
3. promote & deploy to "pre-target"
4. confirm deployment worked (in SFMC); confirm target BU's folder in git master branch (github)
5. try to selectively back-promote 1 user story to 1 prod BU
6. confirm deployment worked (in SFMC); confirm target BU's folder in git master branch (github)
7. try to selectively back-promote 2 user stories at once to 1 prod BU
8. confirm deployment worked (in SFMC); confirm target BU's folder in git master branch (github)
9. try to use mass-backpromote feature to deploy all remaining user stories to both prod BUs
10. confirm deployment worked

**Comment by DannyCastroVentura** [comment]
Tested and working:

- [ ] create multiple changes
- [ ] commit these into separate user stories (sometimes 2 changes, sometimes just 1 per US)
- [ ] promote & deploy to "pre-target"
- [ ] confirm deployment worked (in SFMC); confirm target BU's folder in git master branch (github)
- [ ] try to selectively back-promote 1 user story to 1 prod BU
- [ ] confirm deployment worked (in SFMC); confirm target BU's folder in git master branch (github)
- [ ] try to selectively back-promote 2 user stories at once to 1 prod BU
- [ ] confirm deployment worked (in SFMC); confirm target BU's folder in git master branch (github)
- [ ] try to use mass-backpromote feature to deploy all remaining user stories to both prod BUs
- [ ] confirm deployment worked

**Comment by DannyCastroVentura** [comment]
Content on source:

> Automation in source:
> ![image](https://user-images.githubusercontent.com/72609808/195846536-ccd0ae74-0f86-42a1-a42f-e4f3047395b2.png)
> 
> Asset in source:
> ![image](https://user-images.githubusercontent.com/72609808/195846647-dde6e8c3-8d97-4ebf-940a-49ed99df7bed.png)
> 
> DataExtension in source:
> ![image](https://user-images.githubusercontent.com/72609808/195846695-8a0e4fd4-6967-4613-8acf-6d8fa30ea6f9.png)

Ran deploy into pre-target bu with 2 user storys, one with the dataExtension change, and the other with the automation and asset changes:

> Automation in pre-target:
> ![image](https://user-images.githubusercontent.com/72609808/195847716-98cf7024-deed-4868-851a-5191c0548ba9.png)
> 
> Asset in pre-target:
> ![image](https://user-images.githubusercontent.com/72609808/195847793-82db81fb-e0c2-4e36-8f43-e82c467e7821.png)
> 
> DataExtension in pre-target:
> ![image](https://user-images.githubusercontent.com/72609808/195847861-079ad3e8-8deb-476f-8173-bec333c8129a.png)

Ran back-promote into target_1 bu with 2 user storys, one with the dataExtension change, and the other with the automation and asset changes:

> Automation in target_1:
> ![image](https://user-images.githubusercontent.com/72609808/195845576-7bc29db2-2179-449f-bba5-12cdbe03e8f3.png)
> 
> Asset in target_1:
> ![image](https://user-images.githubusercontent.com/72609808/195845661-affe6d65-c6d0-4021-972e-6c24c2729eaf.png)
> 
> DataExtensions in target_1:
> ![image](https://user-images.githubusercontent.com/72609808/195848195-65645e21-fa40-4e6d-be64-71a964b2e7ef.png)

**Comment by DannyCastroVentura** [comment]
The mass-backpromote all in the same time bug is fixed by this PR: #195 , for this issue #171

**Comment by JoernBerkefeld** [comment]
assuming this test is done successfully now
