### ISSUE TITLE
[BUG] Catch error message when Retrieve function failes

### ISSUE THREAD

**Issue by drcopa** [Accenture/sfmc-devtools-copado#34]
**Current Behavior**
  
When an error occurs while Refreshing metadata in commit page, the user sees no valuable information to resolve the issue.
  
![image (1)](https://user-images.githubusercontent.com/25175105/159897357-549f0f4d-a625-4637-ab95-582bd28ed79f.png)

  
**Expected Behavior**
  
Catch error message returned by Function execution method in apex.
  
  
**Steps To Reproduce**

@DannyCastroVentura  + @anil-sfdc :
1. make retrieve function `throw new Error()` (up top in `run()`) @DannyCastroVentura 
3. Click on Refresh button @anil-sfdc 
4. fix retrieve function again @DannyCastroVentura 
5. reload page @anil-sfdc 
6. make commit function `throw new Error()` (up top in `run()`) @DannyCastroVentura 
7. Click on Commit Changes @anil-sfdc 
8. fix commit function again @DannyCastroVentura 

ideal outcome:
tell the user an error happened and that more details can be found on the related RESULT or JobExectution record that was created for the refresh/commit action

**Comment by anil-sfdc** [comment]
Analysis : look like code update.
 I will try  reproduce  once  created org user.

**Refresh button -> callback->retrieve()**


retrieve(){

          ExecuteRetrieveFromCopado(){

                  try{
	               getMetadataFromEnvironment(){
                        ....
                          }
	            }

     catch( e){
    }

  }
}

**Comment by anil-sfdc** [comment]
it Depend on #103

**Comment by JoernBerkefeld** [comment]
looking back at the original ticket description - have you completely tested those steps and are 100% confident that those cases are now handled?

**Comment by JoernBerkefeld** [comment]
summary of discussion:

tests done until & including step 4. 

steps 5ff still have to be tested

--> **keeping ticket open**

**Comment by anil-sfdc** [comment]
![image](https://user-images.githubusercontent.com/25264884/195051153-dec1776d-bca4-4a1d-ad67-4c442cdf17bc.png)
working as excepted .in step 5

**Comment by JoernBerkefeld** [comment]
uhm ok. but this situation needs to be caught on the COMMIT PAGE.
normal end users don't go to the result page, they stay on the commit page and need to see proper error outputs there.

**Comment by anil-sfdc** [comment]
![Image](https://user-images.githubusercontent.com/25264884/195060117-85fe640a-8418-4529-bdc9-b66dd0937d06.png)

Retrieve error msg

**Comment by JoernBerkefeld** [comment]
thank you Anil
can you please check if we...

- have the Result ID available to us?
- can add an HTML link to the JobExecution record or Result instead of posting the id there?
- can remove the typos and grammar issues from that message?

A good error message could look like this: 

"Refreshing metadata list failed. For more details please go to [this JobExecution](https://google.com) record"

**Comment by anil-sfdc** [comment]
ok.
