### ISSUE TITLE
[TASK] Include MIT License and make project public

### ISSUE THREAD

**Issue by drcopa** [Accenture/sfmc-devtools-copado#36]
This solution is open source and is missing clarification on which open source license it is covered in. 

In the past we had discussed in having the same open source license as MCDEvTools:
https://github.com/Accenture/sfmc-devtools/blob/main/LICENSE

**Comment by JoernBerkefeld** [comment]
with the release to the Accenture org, this becomes urgent

**Comment by JoernBerkefeld** [comment]
done already prior to moving it to the new repo
