### ISSUE TITLE
[BUG] Commit.js has a fixed eid (7281698) in the code

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-copado#4]
replace with an environment variable, not pipeline variable because the EID could be different depending on the environment type (some companies have DEV/QA on one instance/EID and PROD on another, our pilot customer is actually one of them)

```javascript
const authJson = `{
    "credentials": {
        "${credentialName}": {
            "clientId": "${clientId}",
            "clientSecret": "${clientSecret}",
            "tenant": "${tenant}",
            "eid": "7281698"
        }
    }
}`;
```

**Comment by JoernBerkefeld** [comment]
reassigned to you, Danny - can you please check if the code still contains "7281698"? if not, this task was already done and the issue can be closed

**Comment by DannyCastroVentura** [comment]
This was already done, we can close this.
