### ISSUE TITLE
Support more metadata types

### ISSUE THREAD

**Issue by drcopa** [Accenture/sfmc-devtools-copado#5]
Currently only automation and dataExtension metadata types are supported.
Increase the available metadata types to meet parity with SFMC DevTools:

1. asset
2. **automation**
3. **dataExtension**
4. dataExtract
5. emailSendDefinition
6. eventDefinition
7. fileTransfer
8. importFile
9. mobileCode
10. mobileKeyword
11. query
12. role
13. script
14. setDefinition
15. triggeredSendDefinition

**Comment by JoernBerkefeld** [comment]
solved by PR https://github.com/Accenture/sfmc-devtools/pull/285 or rather the release of mcdev 4.0.0: https://github.com/Accenture/sfmc-devtools/releases/tag/v4.0.0
