### ISSUE TITLE
[BUG] table view not sorted on initial load

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-copado#68]
**Current Behavior**
  
data table is not sorted by last modified date as can be clearly seen by the years going up and down.

  
  
**Expected Behavior**
  
data is sorted by last modified date.

  
  
**Steps To Reproduce**
  
when i want to commit components and click on the corresponding button on the user story it takes me to our data table component. there, it loads whatever was previously retrieved and the sorting icon is displayed next to last modified date.

  
  
**Additional comments**

-

**Comment by anil-sfdc** [comment]
Raised PR

**Comment by anil-sfdc** [comment]
Base source code has changes.  it Depended on   #103  after code merged i will update PR
