### ISSUE TITLE
[FEATURE] update "markets" in mcdev config with values from copado GUI

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-copado#79]
- markets will then be auto-written into .mcdevrc.json during runtime, replacing whats in git without updating git

**important:** might already be working. please check if environmentVariables are used to do that in Deploy.js already

this task is dependent on #28

**Comment by JoernBerkefeld** [comment]
currently bllocke by setting up local dev env for deploy.js (#99)

**Comment by DannyCastroVentura** [comment]
Already working.
